'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4016
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class user
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private pseudoField As String
    
    Private chat_allowedField As Byte
    
    Private is_moderateurField As Byte
    
    Private is_adminField As Byte
    
    Private typeField As String
    
    Private metricField As Byte
    
    Private countryField As String
    
    Private quizz_to_respondField As Object
    
    Private full_optionField As Byte
    
    Private option_repair_kitsField As Decimal
    
    Private is_starField As Byte
    
    Private is_winnerField As Byte
    
    Private is_sponsorField As Byte
    
    Private link_sponsorField As Object
    
    Private pict_sponsorField As Object
    
    Private DateOffsetField As String

    Private LochField As Double

    Private couleur4Field As String

    Private couleur5Field As String

    Private preferencesField As String

    Private clef_valideField As Byte

    Private positionField As userPosition

    Private trajectoireField As String

    Private waypointsField As Object

    Private messagesField() As userMessage

    Private nouveaux_amisField As String

    Private opponentsField() As userBoat

    Private amisField() As userBoat2

    Private id_userField As UInteger

    Private dateField As DateTime

    '''<remarks/>
    Public Property pseudo() As String
        Get
            Return Me.pseudoField
        End Get
        Set(ByVal value As String)
            Me.pseudoField = value
            Me.RaisePropertyChanged("pseudo")
        End Set
    End Property

    '''<remarks/>
    Public Property chat_allowed() As Byte
        Get
            Return Me.chat_allowedField
        End Get
        Set(ByVal value As Byte)
            Me.chat_allowedField = value
            Me.RaisePropertyChanged("chat_allowed")
        End Set
    End Property

    '''<remarks/>
    Public Property is_moderateur() As Byte
        Get
            Return Me.is_moderateurField
        End Get
        Set(ByVal value As Byte)
            Me.is_moderateurField = value
            Me.RaisePropertyChanged("is_moderateur")
        End Set
    End Property

    '''<remarks/>
    Public Property is_admin() As Byte
        Get
            Return Me.is_adminField
        End Get
        Set(ByVal value As Byte)
            Me.is_adminField = value
            Me.RaisePropertyChanged("is_admin")
        End Set
    End Property

    '''<remarks/>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set(ByVal value As String)
            Me.typeField = Value
            Me.RaisePropertyChanged("type")
        End Set
    End Property

    '''<remarks/>
    Public Property metric() As Byte
        Get
            Return Me.metricField
        End Get
        Set(ByVal value As Byte)
            Me.metricField = value
            Me.RaisePropertyChanged("metric")
        End Set
    End Property

    '''<remarks/>
    Public Property country() As String
        Get
            Return Me.countryField
        End Get
        Set(ByVal value As String)
            Me.countryField = value
            Me.RaisePropertyChanged("country")
        End Set
    End Property

    '''<remarks/>
    Public Property quizz_to_respond() As Object
        Get
            Return Me.quizz_to_respondField
        End Get
        Set(ByVal value As Object)
            Me.quizz_to_respondField = value
            Me.RaisePropertyChanged("quizz_to_respond")
        End Set
    End Property

    '''<remarks/>
    Public Property full_option() As Byte
        Get
            Return Me.full_optionField
        End Get
        Set(ByVal value As Byte)
            Me.full_optionField = value
            Me.RaisePropertyChanged("full_option")
        End Set
    End Property

    '''<remarks/>
    Public Property option_repair_kits() As Decimal
        Get
            Return Me.option_repair_kitsField
        End Get
        Set(ByVal value As Decimal)
            Me.option_repair_kitsField = value
            Me.RaisePropertyChanged("option_repair_kits")
        End Set
    End Property

    '''<remarks/>
    Public Property is_star() As Byte
        Get
            Return Me.is_starField
        End Get
        Set(ByVal value As Byte)
            Me.is_starField = value
            Me.RaisePropertyChanged("is_star")
        End Set
    End Property

    '''<remarks/>
    Public Property is_winner() As Byte
        Get
            Return Me.is_winnerField
        End Get
        Set(ByVal value As Byte)
            Me.is_winnerField = value
            Me.RaisePropertyChanged("is_winner")
        End Set
    End Property

    '''<remarks/>
    Public Property is_sponsor() As Byte
        Get
            Return Me.is_sponsorField
        End Get
        Set(ByVal value As Byte)
            Me.is_sponsorField = value
            Me.RaisePropertyChanged("is_sponsor")
        End Set
    End Property

    '''<remarks/>
    Public Property link_sponsor() As Object
        Get
            Return Me.link_sponsorField
        End Get
        Set(ByVal value As Object)
            Me.link_sponsorField = value
            Me.RaisePropertyChanged("link_sponsor")
        End Set
    End Property

    '''<remarks/>
    Public Property pict_sponsor() As Object
        Get
            Return Me.pict_sponsorField
        End Get
        Set(ByVal value As Object)
            Me.pict_sponsorField = value
            Me.RaisePropertyChanged("pict_sponsor")
        End Set
    End Property

    '''<remarks/>
    Public Property DateOffset() As Double
        Get
            Return Me.DateOffsetField
        End Get
        Set(ByVal value As Double)
            Me.DateOffsetField = Value
            Me.RaisePropertyChanged("DateOffset")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Loch() As Double
        Get
            Return Me.LochField
        End Get
        Set(ByVal value As Double)
            Me.LochField = value
            Me.RaisePropertyChanged("Loch")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur4() As String
        Get
            Return Me.couleur4Field
        End Get
        Set
            Me.couleur4Field = value
            Me.RaisePropertyChanged("couleur4")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur5() As String
        Get
            Return Me.couleur5Field
        End Get
        Set
            Me.couleur5Field = value
            Me.RaisePropertyChanged("couleur5")
        End Set
    End Property
    
    '''<remarks/>
    Public Property preferences() As String
        Get
            Return Me.preferencesField
        End Get
        Set
            Me.preferencesField = value
            Me.RaisePropertyChanged("preferences")
        End Set
    End Property
    
    '''<remarks/>
    Public Property clef_valide() As Byte
        Get
            Return Me.clef_valideField
        End Get
        Set
            Me.clef_valideField = value
            Me.RaisePropertyChanged("clef_valide")
        End Set
    End Property
    
    '''<remarks/>
    Public Property position() As userPosition
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
            Me.RaisePropertyChanged("position")
        End Set
    End Property
    
    '''<remarks/>
    Public Property trajectoire() As String
        Get
            Return Me.trajectoireField
        End Get
        Set
            Me.trajectoireField = value
            Me.RaisePropertyChanged("trajectoire")
        End Set
    End Property
    
    '''<remarks/>
    Public Property waypoints() As Object
        Get
            Return Me.waypointsField
        End Get
        Set
            Me.waypointsField = value
            Me.RaisePropertyChanged("waypoints")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("message", IsNullable:=false)>  _
    Public Property messages() As userMessage()
        Get
            Return Me.messagesField
        End Get
        Set
            Me.messagesField = value
            Me.RaisePropertyChanged("messages")
        End Set
    End Property
    
    '''<remarks/>
    Public Property nouveaux_amis() As String
        Get
            Return Me.nouveaux_amisField
        End Get
        Set
            Me.nouveaux_amisField = value
            Me.RaisePropertyChanged("nouveaux_amis")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("boat", IsNullable:=false)>  _
    Public Property opponents() As userBoat()
        Get
            Return Me.opponentsField
        End Get
        Set
            Me.opponentsField = value
            Me.RaisePropertyChanged("opponents")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("boat", IsNullable:=false)>  _
    Public Property amis() As userBoat2()
        Get
            Return Me.amisField
        End Get
        Set
            Me.amisField = value
            Me.RaisePropertyChanged("amis")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id_user() As UInteger
        Get
            Return Me.id_userField
        End Get
        Set
            Me.id_userField = value
            Me.RaisePropertyChanged("id_user")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property [date]() As DateTime
        Get
            Return Me.dateField
        End Get
        Set(ByVal value As DateTime)
            Me.dateField = Value
            Me.RaisePropertyChanged("date")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class userPosition
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private latitudeField As Double
    
    Private longitudeField As Double
    
    Private spiField As Byte
    
    Private voileField As UShort
    
    Private voiles_casseesField As Byte
    
    Private vitesseField As Double
    
    Private wind_speedField As Decimal
    
    Private wind_angleField As Double
    
    Private capField As Double
    
    Private distancerestanteField As Decimal
    
    Private distanceparcourueField As Decimal
    
    Private option_assistanceField As Byte
    
    Private _AngleAllure As Double

    Private option_voile_autoField As Byte

    Private option_voile_auto_activatedField As Byte

    Private option_voiles_proField As Byte

    Private option_programField As Byte

    Private option_program_setdateField As String

    Private option_program_autohourField As Byte

    Private option_program_autominutesField As Byte

    Private option_program_autocapField As UShort

    Private option_waypointsField As Byte

    Private classementField As Decimal

    Private isArrivedField As Byte

    Private checkpointField As Byte

    Private id_parcoursField As Byte

    Private id_parcours_xmlField As String

    Private temps_etapeField As String

    Private regimeMoteurField As Byte

    Private ModePiloteField As Integer

    Private eventField As Byte

    Private temps_eventField As String

    Private option_regulateurField As Decimal

    Private option_regulateur_capField As Decimal

    Private diffClassementField As Decimal

    Private dateField As String

    '''<remarks/>
    Public Property latitude() As Double
        Get
            Return Me.latitudeField
        End Get
        Set(ByVal value As Double)
            Me.latitudeField = value
            Me.RaisePropertyChanged("latitude")
        End Set
    End Property

    '''<remarks/>
    Public Property longitude() As Double
        Get
            Return Me.longitudeField
        End Get
        Set(ByVal value As Double)
            Me.longitudeField = value
            Me.RaisePropertyChanged("longitude")
        End Set
    End Property

    '''<remarks/>
    Public Property spi() As Byte
        Get
            Return Me.spiField
        End Get
        Set(ByVal value As Byte)
            Me.spiField = value
            Me.RaisePropertyChanged("spi")
        End Set
    End Property

    '''<remarks/>
    Public Property voile() As UShort
        Get
            Return Me.voileField
        End Get
        Set(ByVal value As UShort)
            Me.voileField = value
            Me.RaisePropertyChanged("voile")
        End Set
    End Property

    '''<remarks/>
    Public Property voiles_cassees() As Byte
        Get
            Return Me.voiles_casseesField
        End Get
        Set(ByVal value As Byte)
            Me.voiles_casseesField = value
            Me.RaisePropertyChanged("voiles_cassees")
        End Set
    End Property

    '''<remarks/>
    Public Property vitesse() As Double
        Get
            Return Me.vitesseField
        End Get
        Set(ByVal value As Double)
            Me.vitesseField = value
            Me.RaisePropertyChanged("vitesse")
        End Set
    End Property

    '''<remarks/>
    Public Property wind_speed() As Double
        Get
            Return Me.wind_speedField
        End Get
        Set(ByVal value As Double)
            Me.wind_speedField = value
            Me.RaisePropertyChanged("wind_speed")
        End Set
    End Property

    '''<remarks/>
    Public Property wind_angle() As Double
        Get
            Return Me.wind_angleField
        End Get
        Set(ByVal value As Double)
            Me.wind_angleField = Value
            Me.RaisePropertyChanged("wind_angle")
        End Set
    End Property

    '''<remarks/>
    Public Property cap() As Double
        Get
            Return Me.capField
        End Get
        Set(ByVal value As Double)
            Me.capField = Value
            Me.RaisePropertyChanged("cap")
        End Set
    End Property

    '''<remarks/>
    Public Property distancerestante() As Decimal
        Get
            Return Me.distancerestanteField
        End Get
        Set(ByVal value As Decimal)
            Me.distancerestanteField = value
            Me.RaisePropertyChanged("distancerestante")
        End Set
    End Property

    '''<remarks/>
    Public Property distanceparcourue() As Decimal
        Get
            Return Me.distanceparcourueField
        End Get
        Set(ByVal value As Decimal)
            Me.distanceparcourueField = value
            Me.RaisePropertyChanged("distanceparcourue")
        End Set
    End Property

    '''<remarks/>
    Public Property option_assistance() As Byte
        Get
            Return Me.option_assistanceField
        End Get
        Set(ByVal value As Byte)
            Me.option_assistanceField = value
            Me.RaisePropertyChanged("option_assistance")
        End Set
    End Property

    '''<remarks/>
    Public Property AngleAllure() As Double
        Get
            Return Me._AngleAllure
        End Get
        Set(ByVal value As Double)
            Me._AngleAllure = value
            Me.RaisePropertyChanged("AngleAllure")
        End Set
    End Property

    '''<remarks/>
    Public Property option_voile_auto() As Byte
        Get
            Return Me.option_voile_autoField
        End Get
        Set(ByVal value As Byte)
            Me.option_voile_autoField = value
            Me.RaisePropertyChanged("option_voile_auto")
        End Set
    End Property

    '''<remarks/>
    Public Property option_voile_auto_activated() As Byte
        Get
            Return Me.option_voile_auto_activatedField
        End Get
        Set(ByVal value As Byte)
            Me.option_voile_auto_activatedField = value
            Me.RaisePropertyChanged("option_voile_auto_activated")
        End Set
    End Property

    '''<remarks/>
    Public Property option_voiles_pro() As Byte
        Get
            Return Me.option_voiles_proField
        End Get
        Set(ByVal value As Byte)
            Me.option_voiles_proField = value
            Me.RaisePropertyChanged("option_voiles_pro")
        End Set
    End Property

    '''<remarks/>
    Public Property option_program() As Byte
        Get
            Return Me.option_programField
        End Get
        Set(ByVal value As Byte)
            Me.option_programField = value
            Me.RaisePropertyChanged("option_program")
        End Set
    End Property

    '''<remarks/>
    Public Property option_program_setdate() As String
        Get
            Return Me.option_program_setdateField
        End Get
        Set(ByVal value As String)
            Me.option_program_setdateField = value
            Me.RaisePropertyChanged("option_program_setdate")
        End Set
    End Property

    '''<remarks/>
    Public Property option_program_autohour() As Byte
        Get
            Return Me.option_program_autohourField
        End Get
        Set(ByVal value As Byte)
            Me.option_program_autohourField = value
            Me.RaisePropertyChanged("option_program_autohour")
        End Set
    End Property

    '''<remarks/>
    Public Property option_program_autominutes() As Byte
        Get
            Return Me.option_program_autominutesField
        End Get
        Set(ByVal value As Byte)
            Me.option_program_autominutesField = value
            Me.RaisePropertyChanged("option_program_autominutes")
        End Set
    End Property

    '''<remarks/>
    Public Property option_program_autocap() As UShort
        Get
            Return Me.option_program_autocapField
        End Get
        Set(ByVal value As UShort)
            Me.option_program_autocapField = value
            Me.RaisePropertyChanged("option_program_autocap")
        End Set
    End Property

    '''<remarks/>
    Public Property option_waypoints() As Byte
        Get
            Return Me.option_waypointsField
        End Get
        Set(ByVal value As Byte)
            Me.option_waypointsField = value
            Me.RaisePropertyChanged("option_waypoints")
        End Set
    End Property

    '''<remarks/>
    Public Property classement() As Decimal
        Get
            Return Me.classementField
        End Get
        Set(ByVal value As Decimal)
            Me.classementField = value
            Me.RaisePropertyChanged("classement")
        End Set
    End Property

    '''<remarks/>
    Public Property IsArrived() As Byte
        Get
            Return Me.isArrivedField
        End Get
        Set(ByVal value As Byte)
            Me.isArrivedField = value
            Me.RaisePropertyChanged("IsArrived")
        End Set
    End Property

    '''<remarks/>
    Public Property checkpoint() As Byte
        Get
            Return Me.checkpointField
        End Get
        Set(ByVal value As Byte)
            Me.checkpointField = value
            Me.RaisePropertyChanged("checkpoint")
        End Set
    End Property

    '''<remarks/>
    Public Property id_parcours() As Byte
        Get
            Return Me.id_parcoursField
        End Get
        Set(ByVal value As Byte)
            Me.id_parcoursField = value
            Me.RaisePropertyChanged("id_parcours")
        End Set
    End Property

    '''<remarks/>
    Public Property id_parcours_xml() As String
        Get
            Return Me.id_parcours_xmlField
        End Get
        Set(ByVal value As String)
            Me.id_parcours_xmlField = value
            Me.RaisePropertyChanged("id_parcours_xml")
        End Set
    End Property

    '''<remarks/>
    Public Property temps_etape() As String
        Get
            Return Me.temps_etapeField
        End Get
        Set(ByVal value As String)
            Me.temps_etapeField = value
            Me.RaisePropertyChanged("temps_etape")
        End Set
    End Property

    '''<remarks/>
    Public Property RegimeMoteur() As Byte
        Get
            Return Me.regimeMoteurField
        End Get
        Set(ByVal value As Byte)
            Me.regimeMoteurField = value
            Me.RaisePropertyChanged("RegimeMoteur")
        End Set
    End Property

    '''<remarks/>
    Public Property ModePilote() As Integer
        Get
            Return Me.ModePiloteField
        End Get
        Set(ByVal value As Integer)
            Me.ModePiloteField = value
            Me.RaisePropertyChanged("ModePilote")
        End Set
    End Property
    
    '''<remarks/>
    Public Property [event]() As Byte
        Get
            Return Me.eventField
        End Get
        Set
            Me.eventField = value
            Me.RaisePropertyChanged("event")
        End Set
    End Property
    
    '''<remarks/>
    Public Property temps_event() As String
        Get
            Return Me.temps_eventField
        End Get
        Set
            Me.temps_eventField = value
            Me.RaisePropertyChanged("temps_event")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_regulateur() As Decimal
        Get
            Return Me.option_regulateurField
        End Get
        Set
            Me.option_regulateurField = value
            Me.RaisePropertyChanged("option_regulateur")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_regulateur_cap() As Decimal
        Get
            Return Me.option_regulateur_capField
        End Get
        Set
            Me.option_regulateur_capField = value
            Me.RaisePropertyChanged("option_regulateur_cap")
        End Set
    End Property
    
    '''<remarks/>
    Public Property diffClassement() As Decimal
        Get
            Return Me.diffClassementField
        End Get
        Set
            Me.diffClassementField = value
            Me.RaisePropertyChanged("diffClassement")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property [date]() As String
        Get
            Return Me.dateField
        End Get
        Set
            Me.dateField = value
            Me.RaisePropertyChanged("date")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class userMessage
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private senderField As userMessageSender
    
    Private textField As String
    
    Private idField As UInteger
    
    '''<remarks/>
    Public Property sender() As userMessageSender
        Get
            Return Me.senderField
        End Get
        Set
            Me.senderField = value
            Me.RaisePropertyChanged("sender")
        End Set
    End Property
    
    '''<remarks/>
    Public Property text() As String
        Get
            Return Me.textField
        End Get
        Set
            Me.textField = value
            Me.RaisePropertyChanged("text")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As UInteger
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
            Me.RaisePropertyChanged("id")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class userMessageSender
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private id_userField As UInteger
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id_user() As UInteger
        Get
            Return Me.id_userField
        End Get
        Set
            Me.id_userField = value
            Me.RaisePropertyChanged("id_user")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
            Me.RaisePropertyChanged("Value")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class userBoat
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private pseudoField As String
    
    Private is_moderateurField As Byte
    
    Private typeField As Byte
    
    Private metricField As Byte
    
    Private countryField As Object
    
    Private full_optionField As Byte
    
    Private option_repair_kitsField As Decimal
    
    Private is_sponsorField As Byte
    
    Private link_sponsorField As Object
    
    Private pict_sponsorField As String
    
    Private is_starField As Byte
    
    Private is_winnerField As Byte
    
    Private couleur1Field As String
    
    Private couleur2Field As String
    
    Private couleur3Field As String
    
    Private couleur4Field As String
    
    Private couleur5Field As String
    
    Private longitudeField As Double
    
    Private latitudeField As Double
    
    Private spiField As Byte
    
    Private voileField As UShort
    
    Private voiles_casseesField As Byte
    
    Private vitesseField As Decimal
    
    Private wind_speedField As Decimal
    
    Private wind_angleField As Byte
    
    Private capField As Short
    
    Private distancerestanteField As Decimal
    
    Private distanceparcourueField As Decimal
    
    Private option_assistanceField As Byte
    
    Private option_vigilanceField As Byte
    
    Private option_voile_autoField As Byte
    
    Private option_voile_auto_activatedField As Byte
    
    Private option_voiles_proField As Byte
    
    Private option_programField As Byte
    
    Private classementField As Decimal
    
    Private isArrivedField As Byte
    
    Private temps_etapeField As String
    
    Private regimeMoteurField As Byte
    
    Private carburantField As Byte
    
    Private option_regulateurField As Decimal
    
    Private amisField() As String
    
    Private trajectoireField As String
    
    Private id_userField As UInteger
    
    '''<remarks/>
    Public Property pseudo() As String
        Get
            Return Me.pseudoField
        End Get
        Set
            Me.pseudoField = value
            Me.RaisePropertyChanged("pseudo")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_moderateur() As Byte
        Get
            Return Me.is_moderateurField
        End Get
        Set
            Me.is_moderateurField = value
            Me.RaisePropertyChanged("is_moderateur")
        End Set
    End Property
    
    '''<remarks/>
    Public Property type() As Byte
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
            Me.RaisePropertyChanged("type")
        End Set
    End Property
    
    '''<remarks/>
    Public Property metric() As Byte
        Get
            Return Me.metricField
        End Get
        Set
            Me.metricField = value
            Me.RaisePropertyChanged("metric")
        End Set
    End Property
    
    '''<remarks/>
    Public Property country() As Object
        Get
            Return Me.countryField
        End Get
        Set
            Me.countryField = value
            Me.RaisePropertyChanged("country")
        End Set
    End Property
    
    '''<remarks/>
    Public Property full_option() As Byte
        Get
            Return Me.full_optionField
        End Get
        Set
            Me.full_optionField = value
            Me.RaisePropertyChanged("full_option")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_repair_kits() As Decimal
        Get
            Return Me.option_repair_kitsField
        End Get
        Set
            Me.option_repair_kitsField = value
            Me.RaisePropertyChanged("option_repair_kits")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_sponsor() As Byte
        Get
            Return Me.is_sponsorField
        End Get
        Set
            Me.is_sponsorField = value
            Me.RaisePropertyChanged("is_sponsor")
        End Set
    End Property
    
    '''<remarks/>
    Public Property link_sponsor() As Object
        Get
            Return Me.link_sponsorField
        End Get
        Set
            Me.link_sponsorField = value
            Me.RaisePropertyChanged("link_sponsor")
        End Set
    End Property
    
    '''<remarks/>
    Public Property pict_sponsor() As String
        Get
            Return Me.pict_sponsorField
        End Get
        Set
            Me.pict_sponsorField = value
            Me.RaisePropertyChanged("pict_sponsor")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_star() As Byte
        Get
            Return Me.is_starField
        End Get
        Set
            Me.is_starField = value
            Me.RaisePropertyChanged("is_star")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_winner() As Byte
        Get
            Return Me.is_winnerField
        End Get
        Set
            Me.is_winnerField = value
            Me.RaisePropertyChanged("is_winner")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur1() As String
        Get
            Return Me.couleur1Field
        End Get
        Set
            Me.couleur1Field = value
            Me.RaisePropertyChanged("couleur1")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur2() As String
        Get
            Return Me.couleur2Field
        End Get
        Set
            Me.couleur2Field = value
            Me.RaisePropertyChanged("couleur2")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur3() As String
        Get
            Return Me.couleur3Field
        End Get
        Set
            Me.couleur3Field = value
            Me.RaisePropertyChanged("couleur3")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur4() As String
        Get
            Return Me.couleur4Field
        End Get
        Set
            Me.couleur4Field = value
            Me.RaisePropertyChanged("couleur4")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur5() As String
        Get
            Return Me.couleur5Field
        End Get
        Set
            Me.couleur5Field = value
            Me.RaisePropertyChanged("couleur5")
        End Set
    End Property
    
    '''<remarks/>
    Public Property longitude() As Double
        Get
            Return Me.longitudeField
        End Get
        Set
            Me.longitudeField = value
            Me.RaisePropertyChanged("longitude")
        End Set
    End Property
    
    '''<remarks/>
    Public Property latitude() As Double
        Get
            Return Me.latitudeField
        End Get
        Set
            Me.latitudeField = value
            Me.RaisePropertyChanged("latitude")
        End Set
    End Property
    
    '''<remarks/>
    Public Property spi() As Byte
        Get
            Return Me.spiField
        End Get
        Set
            Me.spiField = value
            Me.RaisePropertyChanged("spi")
        End Set
    End Property
    
    '''<remarks/>
    Public Property voile() As UShort
        Get
            Return Me.voileField
        End Get
        Set
            Me.voileField = value
            Me.RaisePropertyChanged("voile")
        End Set
    End Property
    
    '''<remarks/>
    Public Property voiles_cassees() As Byte
        Get
            Return Me.voiles_casseesField
        End Get
        Set
            Me.voiles_casseesField = value
            Me.RaisePropertyChanged("voiles_cassees")
        End Set
    End Property
    
    '''<remarks/>
    Public Property vitesse() As Decimal
        Get
            Return Me.vitesseField
        End Get
        Set
            Me.vitesseField = value
            Me.RaisePropertyChanged("vitesse")
        End Set
    End Property
    
    '''<remarks/>
    Public Property wind_speed() As Decimal
        Get
            Return Me.wind_speedField
        End Get
        Set
            Me.wind_speedField = value
            Me.RaisePropertyChanged("wind_speed")
        End Set
    End Property
    
    '''<remarks/>
    Public Property wind_angle() As Byte
        Get
            Return Me.wind_angleField
        End Get
        Set
            Me.wind_angleField = value
            Me.RaisePropertyChanged("wind_angle")
        End Set
    End Property
    
    '''<remarks/>
    Public Property cap() As Short
        Get
            Return Me.capField
        End Get
        Set
            Me.capField = value
            Me.RaisePropertyChanged("cap")
        End Set
    End Property
    
    '''<remarks/>
    Public Property distancerestante() As Decimal
        Get
            Return Me.distancerestanteField
        End Get
        Set
            Me.distancerestanteField = value
            Me.RaisePropertyChanged("distancerestante")
        End Set
    End Property
    
    '''<remarks/>
    Public Property distanceparcourue() As Decimal
        Get
            Return Me.distanceparcourueField
        End Get
        Set
            Me.distanceparcourueField = value
            Me.RaisePropertyChanged("distanceparcourue")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_assistance() As Byte
        Get
            Return Me.option_assistanceField
        End Get
        Set
            Me.option_assistanceField = value
            Me.RaisePropertyChanged("option_assistance")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_vigilance() As Byte
        Get
            Return Me.option_vigilanceField
        End Get
        Set
            Me.option_vigilanceField = value
            Me.RaisePropertyChanged("option_vigilance")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_voile_auto() As Byte
        Get
            Return Me.option_voile_autoField
        End Get
        Set
            Me.option_voile_autoField = value
            Me.RaisePropertyChanged("option_voile_auto")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_voile_auto_activated() As Byte
        Get
            Return Me.option_voile_auto_activatedField
        End Get
        Set
            Me.option_voile_auto_activatedField = value
            Me.RaisePropertyChanged("option_voile_auto_activated")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_voiles_pro() As Byte
        Get
            Return Me.option_voiles_proField
        End Get
        Set
            Me.option_voiles_proField = value
            Me.RaisePropertyChanged("option_voiles_pro")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_program() As Byte
        Get
            Return Me.option_programField
        End Get
        Set
            Me.option_programField = value
            Me.RaisePropertyChanged("option_program")
        End Set
    End Property
    
    '''<remarks/>
    Public Property classement() As Decimal
        Get
            Return Me.classementField
        End Get
        Set
            Me.classementField = value
            Me.RaisePropertyChanged("classement")
        End Set
    End Property
    
    '''<remarks/>
    Public Property IsArrived() As Byte
        Get
            Return Me.isArrivedField
        End Get
        Set
            Me.isArrivedField = value
            Me.RaisePropertyChanged("IsArrived")
        End Set
    End Property
    
    '''<remarks/>
    Public Property temps_etape() As String
        Get
            Return Me.temps_etapeField
        End Get
        Set
            Me.temps_etapeField = value
            Me.RaisePropertyChanged("temps_etape")
        End Set
    End Property
    
    '''<remarks/>
    Public Property RegimeMoteur() As Byte
        Get
            Return Me.regimeMoteurField
        End Get
        Set
            Me.regimeMoteurField = value
            Me.RaisePropertyChanged("RegimeMoteur")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Carburant() As Byte
        Get
            Return Me.carburantField
        End Get
        Set
            Me.carburantField = value
            Me.RaisePropertyChanged("Carburant")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_regulateur() As Decimal
        Get
            Return Me.option_regulateurField
        End Get
        Set
            Me.option_regulateurField = value
            Me.RaisePropertyChanged("option_regulateur")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("boat", IsNullable:=false)>  _
    Public Property amis() As String()
        Get
            Return Me.amisField
        End Get
        Set
            Me.amisField = value
            Me.RaisePropertyChanged("amis")
        End Set
    End Property
    
    '''<remarks/>
    Public Property trajectoire() As String
        Get
            Return Me.trajectoireField
        End Get
        Set
            Me.trajectoireField = value
            Me.RaisePropertyChanged("trajectoire")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id_user() As UInteger
        Get
            Return Me.id_userField
        End Get
        Set
            Me.id_userField = value
            Me.RaisePropertyChanged("id_user")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class userBoat2
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private pseudoField As String
    
    Private is_moderateurField As Byte
    
    Private typeField As Byte
    
    Private metricField As Byte
    
    Private countryField As String
    
    Private full_optionField As Byte
    
    Private option_repair_kitsField As Decimal
    
    Private is_sponsorField As Byte
    
    Private link_sponsorField As Object
    
    Private pict_sponsorField As Object
    
    Private is_starField As Byte
    
    Private is_winnerField As Byte
    
    Private couleur1Field As String
    
    Private couleur2Field As String
    
    Private couleur3Field As String
    
    Private couleur4Field As String
    
    Private couleur5Field As String
    
    Private longitudeField As Double
    
    Private latitudeField As Double
    
    Private spiField As Byte
    
    Private voileField As UShort
    
    Private voiles_casseesField As Byte
    
    Private vitesseField As Decimal
    
    Private wind_speedField As Decimal
    
    Private wind_angleField As Byte
    
    Private capField As Short
    
    Private distancerestanteField As Decimal
    
    Private distanceparcourueField As Decimal
    
    Private option_assistanceField As Byte
    
    Private option_vigilanceField As Byte
    
    Private option_voile_autoField As Byte
    
    Private option_voile_auto_activatedField As Byte
    
    Private option_voiles_proField As Byte
    
    Private option_programField As Byte
    
    Private classementField As Decimal
    
    Private isArrivedField As Byte
    
    Private temps_etapeField As String
    
    Private regimeMoteurField As Byte
    
    Private carburantField As Byte
    
    Private option_regulateurField As Decimal
    
    Private amisField() As String
    
    Private trajectoireField As String
    
    Private id_userField As UInteger
    
    '''<remarks/>
    Public Property pseudo() As String
        Get
            Return Me.pseudoField
        End Get
        Set
            Me.pseudoField = value
            Me.RaisePropertyChanged("pseudo")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_moderateur() As Byte
        Get
            Return Me.is_moderateurField
        End Get
        Set
            Me.is_moderateurField = value
            Me.RaisePropertyChanged("is_moderateur")
        End Set
    End Property
    
    '''<remarks/>
    Public Property type() As Byte
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
            Me.RaisePropertyChanged("type")
        End Set
    End Property
    
    '''<remarks/>
    Public Property metric() As Byte
        Get
            Return Me.metricField
        End Get
        Set
            Me.metricField = value
            Me.RaisePropertyChanged("metric")
        End Set
    End Property
    
    '''<remarks/>
    Public Property country() As String
        Get
            Return Me.countryField
        End Get
        Set
            Me.countryField = value
            Me.RaisePropertyChanged("country")
        End Set
    End Property
    
    '''<remarks/>
    Public Property full_option() As Byte
        Get
            Return Me.full_optionField
        End Get
        Set
            Me.full_optionField = value
            Me.RaisePropertyChanged("full_option")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_repair_kits() As Decimal
        Get
            Return Me.option_repair_kitsField
        End Get
        Set
            Me.option_repair_kitsField = value
            Me.RaisePropertyChanged("option_repair_kits")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_sponsor() As Byte
        Get
            Return Me.is_sponsorField
        End Get
        Set
            Me.is_sponsorField = value
            Me.RaisePropertyChanged("is_sponsor")
        End Set
    End Property
    
    '''<remarks/>
    Public Property link_sponsor() As Object
        Get
            Return Me.link_sponsorField
        End Get
        Set
            Me.link_sponsorField = value
            Me.RaisePropertyChanged("link_sponsor")
        End Set
    End Property
    
    '''<remarks/>
    Public Property pict_sponsor() As Object
        Get
            Return Me.pict_sponsorField
        End Get
        Set
            Me.pict_sponsorField = value
            Me.RaisePropertyChanged("pict_sponsor")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_star() As Byte
        Get
            Return Me.is_starField
        End Get
        Set
            Me.is_starField = value
            Me.RaisePropertyChanged("is_star")
        End Set
    End Property
    
    '''<remarks/>
    Public Property is_winner() As Byte
        Get
            Return Me.is_winnerField
        End Get
        Set
            Me.is_winnerField = value
            Me.RaisePropertyChanged("is_winner")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur1() As String
        Get
            Return Me.couleur1Field
        End Get
        Set
            Me.couleur1Field = value
            Me.RaisePropertyChanged("couleur1")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur2() As String
        Get
            Return Me.couleur2Field
        End Get
        Set
            Me.couleur2Field = value
            Me.RaisePropertyChanged("couleur2")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur3() As String
        Get
            Return Me.couleur3Field
        End Get
        Set
            Me.couleur3Field = value
            Me.RaisePropertyChanged("couleur3")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur4() As String
        Get
            Return Me.couleur4Field
        End Get
        Set
            Me.couleur4Field = value
            Me.RaisePropertyChanged("couleur4")
        End Set
    End Property
    
    '''<remarks/>
    Public Property couleur5() As String
        Get
            Return Me.couleur5Field
        End Get
        Set
            Me.couleur5Field = value
            Me.RaisePropertyChanged("couleur5")
        End Set
    End Property
    
    '''<remarks/>
    Public Property longitude() As Double
        Get
            Return Me.longitudeField
        End Get
        Set
            Me.longitudeField = value
            Me.RaisePropertyChanged("longitude")
        End Set
    End Property
    
    '''<remarks/>
    Public Property latitude() As Double
        Get
            Return Me.latitudeField
        End Get
        Set
            Me.latitudeField = value
            Me.RaisePropertyChanged("latitude")
        End Set
    End Property
    
    '''<remarks/>
    Public Property spi() As Byte
        Get
            Return Me.spiField
        End Get
        Set
            Me.spiField = value
            Me.RaisePropertyChanged("spi")
        End Set
    End Property
    
    '''<remarks/>
    Public Property voile() As UShort
        Get
            Return Me.voileField
        End Get
        Set
            Me.voileField = value
            Me.RaisePropertyChanged("voile")
        End Set
    End Property
    
    '''<remarks/>
    Public Property voiles_cassees() As Byte
        Get
            Return Me.voiles_casseesField
        End Get
        Set
            Me.voiles_casseesField = value
            Me.RaisePropertyChanged("voiles_cassees")
        End Set
    End Property
    
    '''<remarks/>
    Public Property vitesse() As Decimal
        Get
            Return Me.vitesseField
        End Get
        Set
            Me.vitesseField = value
            Me.RaisePropertyChanged("vitesse")
        End Set
    End Property
    
    '''<remarks/>
    Public Property wind_speed() As Decimal
        Get
            Return Me.wind_speedField
        End Get
        Set
            Me.wind_speedField = value
            Me.RaisePropertyChanged("wind_speed")
        End Set
    End Property
    
    '''<remarks/>
    Public Property wind_angle() As Byte
        Get
            Return Me.wind_angleField
        End Get
        Set
            Me.wind_angleField = value
            Me.RaisePropertyChanged("wind_angle")
        End Set
    End Property
    
    '''<remarks/>
    Public Property cap() As Short
        Get
            Return Me.capField
        End Get
        Set
            Me.capField = value
            Me.RaisePropertyChanged("cap")
        End Set
    End Property
    
    '''<remarks/>
    Public Property distancerestante() As Decimal
        Get
            Return Me.distancerestanteField
        End Get
        Set
            Me.distancerestanteField = value
            Me.RaisePropertyChanged("distancerestante")
        End Set
    End Property
    
    '''<remarks/>
    Public Property distanceparcourue() As Decimal
        Get
            Return Me.distanceparcourueField
        End Get
        Set
            Me.distanceparcourueField = value
            Me.RaisePropertyChanged("distanceparcourue")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_assistance() As Byte
        Get
            Return Me.option_assistanceField
        End Get
        Set
            Me.option_assistanceField = value
            Me.RaisePropertyChanged("option_assistance")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_vigilance() As Byte
        Get
            Return Me.option_vigilanceField
        End Get
        Set
            Me.option_vigilanceField = value
            Me.RaisePropertyChanged("option_vigilance")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_voile_auto() As Byte
        Get
            Return Me.option_voile_autoField
        End Get
        Set
            Me.option_voile_autoField = value
            Me.RaisePropertyChanged("option_voile_auto")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_voile_auto_activated() As Byte
        Get
            Return Me.option_voile_auto_activatedField
        End Get
        Set
            Me.option_voile_auto_activatedField = value
            Me.RaisePropertyChanged("option_voile_auto_activated")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_voiles_pro() As Byte
        Get
            Return Me.option_voiles_proField
        End Get
        Set
            Me.option_voiles_proField = value
            Me.RaisePropertyChanged("option_voiles_pro")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_program() As Byte
        Get
            Return Me.option_programField
        End Get
        Set
            Me.option_programField = value
            Me.RaisePropertyChanged("option_program")
        End Set
    End Property
    
    '''<remarks/>
    Public Property classement() As Decimal
        Get
            Return Me.classementField
        End Get
        Set
            Me.classementField = value
            Me.RaisePropertyChanged("classement")
        End Set
    End Property
    
    '''<remarks/>
    Public Property IsArrived() As Byte
        Get
            Return Me.isArrivedField
        End Get
        Set
            Me.isArrivedField = value
            Me.RaisePropertyChanged("IsArrived")
        End Set
    End Property
    
    '''<remarks/>
    Public Property temps_etape() As String
        Get
            Return Me.temps_etapeField
        End Get
        Set
            Me.temps_etapeField = value
            Me.RaisePropertyChanged("temps_etape")
        End Set
    End Property
    
    '''<remarks/>
    Public Property RegimeMoteur() As Byte
        Get
            Return Me.regimeMoteurField
        End Get
        Set
            Me.regimeMoteurField = value
            Me.RaisePropertyChanged("RegimeMoteur")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Carburant() As Byte
        Get
            Return Me.carburantField
        End Get
        Set
            Me.carburantField = value
            Me.RaisePropertyChanged("Carburant")
        End Set
    End Property
    
    '''<remarks/>
    Public Property option_regulateur() As Decimal
        Get
            Return Me.option_regulateurField
        End Get
        Set
            Me.option_regulateurField = value
            Me.RaisePropertyChanged("option_regulateur")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("boat", IsNullable:=false)>  _
    Public Property amis() As String()
        Get
            Return Me.amisField
        End Get
        Set
            Me.amisField = value
            Me.RaisePropertyChanged("amis")
        End Set
    End Property
    
    '''<remarks/>
    Public Property trajectoire() As String
        Get
            Return Me.trajectoireField
        End Get
        Set
            Me.trajectoireField = value
            Me.RaisePropertyChanged("trajectoire")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id_user() As UInteger
        Get
            Return Me.id_userField
        End Get
        Set
            Me.id_userField = value
            Me.RaisePropertyChanged("id_user")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class
