'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.4016
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.3038.
'
Namespace currents
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
    Partial Public Class PREVISIONS
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pREVISIONField As PREVISIONSPREVISION
        
        Private cOLSField As Byte
        
        Private rOWSField As Byte
        
        Private lONGITUDESTARTField As Decimal
        
        Private lATITUDESTARTField As Decimal
        
        Private dxField As Decimal
        
        Private dyField As Decimal
        
        '''<remarks/>
        Public Property PREVISION() As PREVISIONSPREVISION
            Get
                Return Me.pREVISIONField
            End Get
            Set
                Me.pREVISIONField = value
                Me.RaisePropertyChanged("PREVISION")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property COLS() As Byte
            Get
                Return Me.cOLSField
            End Get
            Set
                Me.cOLSField = value
                Me.RaisePropertyChanged("COLS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ROWS() As Byte
            Get
                Return Me.rOWSField
            End Get
            Set
                Me.rOWSField = value
                Me.RaisePropertyChanged("ROWS")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property LONGITUDESTART() As Decimal
            Get
                Return Me.lONGITUDESTARTField
            End Get
            Set
                Me.lONGITUDESTARTField = value
                Me.RaisePropertyChanged("LONGITUDESTART")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property LATITUDESTART() As Decimal
            Get
                Return Me.lATITUDESTARTField
            End Get
            Set
                Me.lATITUDESTARTField = value
                Me.RaisePropertyChanged("LATITUDESTART")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property DX() As Decimal
            Get
                Return Me.dxField
            End Get
            Set
                Me.dxField = value
                Me.RaisePropertyChanged("DX")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property DY() As Decimal
            Get
                Return Me.dyField
            End Get
            Set
                Me.dyField = value
                Me.RaisePropertyChanged("DY")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class PREVISIONSPREVISION
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dAYField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property DAY() As String
            Get
                Return Me.dAYField
            End Get
            Set
                Me.dAYField = value
                Me.RaisePropertyChanged("DAY")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
End Namespace
