'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.5420
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Ce code source a été automatiquement généré par xsd, Version=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _
Partial Public Class RouteExport
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private generatorField As Generator
    
    Private routeListField As RouteExportRouteList
    
    '''<remarks/>
    Public Property Generator() As Generator
        Get
            Return Me.generatorField
        End Get
        Set
            Me.generatorField = value
            Me.RaisePropertyChanged("Generator")
        End Set
    End Property
    
    '''<remarks/>
    Public Property RouteList() As RouteExportRouteList
        Get
            Return Me.routeListField
        End Get
        Set
            Me.routeListField = value
            Me.RaisePropertyChanged("RouteList")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class Generator
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private nameField As String
    
    Private versionField As String
    
    Private exportDateField As Date
    
    '''<remarks/>
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
            Me.RaisePropertyChanged("Name")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
            Me.RaisePropertyChanged("Version")
        End Set
    End Property
    
    '''<remarks/>
    Public Property ExportDate() As Date
        Get
            Return Me.exportDateField
        End Get
        Set
            Me.exportDateField = value
            Me.RaisePropertyChanged("ExportDate")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class RouteCoords
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private lonField As Double
    
    Private latField As Double
    
    '''<remarks/>
    Public Property Lon() As Double
        Get
            Return Me.lonField
        End Get
        Set
            Me.lonField = value
            Me.RaisePropertyChanged("Lon")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Lat() As Double
        Get
            Return Me.latField
        End Get
        Set
            Me.latField = value
            Me.RaisePropertyChanged("Lat")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class WPActionValue
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private wpField As RouteCoords
    
    Private angleAtWPField As Double
    
    Private angleAtWPFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property WP() As RouteCoords
        Get
            Return Me.wpField
        End Get
        Set
            Me.wpField = value
            Me.RaisePropertyChanged("WP")
        End Set
    End Property
    
    '''<remarks/>
    Public Property AngleAtWP() As Double
        Get
            Return Me.angleAtWPField
        End Get
        Set
            Me.angleAtWPField = value
            Me.RaisePropertyChanged("AngleAtWP")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property AngleAtWPSpecified() As Boolean
        Get
            Return Me.angleAtWPFieldSpecified
        End Get
        Set
            Me.angleAtWPFieldSpecified = value
            Me.RaisePropertyChanged("AngleAtWPSpecified")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class RoutePoint
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private actionDateField As Date
    
    Private typeField As RouteActionType
    
    Private actionValueField As RoutePointActionValue
    
    Private coordsField As RouteCoords
    
    '''<remarks/>
    Public Property ActionDate() As Date
        Get
            Return Me.actionDateField
        End Get
        Set
            Me.actionDateField = value
            Me.RaisePropertyChanged("ActionDate")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Type() As RouteActionType
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
            Me.RaisePropertyChanged("Type")
        End Set
    End Property
    
    '''<remarks/>
    Public Property ActionValue() As RoutePointActionValue
        Get
            Return Me.actionValueField
        End Get
        Set
            Me.actionValueField = value
            Me.RaisePropertyChanged("ActionValue")
        End Set
    End Property
    
    '''<remarks/>
    Public Property Coords() As RouteCoords
        Get
            Return Me.coordsField
        End Get
        Set
            Me.coordsField = value
            Me.RaisePropertyChanged("Coords")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute()>  _
Public Enum RouteActionType
    
    '''<remarks/>
    Bearing
    
    '''<remarks/>
    Angle
    
    '''<remarks/>
    Ortho
    
    '''<remarks/>
    VMG
    
    '''<remarks/>
    VBVMG
    
    '''<remarks/>
    HISTORY
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class RoutePointActionValue
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private itemField As Object
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("DoubleAction", GetType(Double)),  _
     System.Xml.Serialization.XmlElementAttribute("WPAction", GetType(WPActionValue))>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
            Me.RaisePropertyChanged("Item")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class RouteColor
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private rField As Byte
    
    Private gField As Byte
    
    Private bField As Byte
    
    Private aField As Byte
    
    '''<remarks/>
    Public Property R() As Byte
        Get
            Return Me.rField
        End Get
        Set
            Me.rField = value
            Me.RaisePropertyChanged("R")
        End Set
    End Property
    
    '''<remarks/>
    Public Property G() As Byte
        Get
            Return Me.gField
        End Get
        Set
            Me.gField = value
            Me.RaisePropertyChanged("G")
        End Set
    End Property
    
    '''<remarks/>
    Public Property B() As Byte
        Get
            Return Me.bField
        End Get
        Set
            Me.bField = value
            Me.RaisePropertyChanged("B")
        End Set
    End Property
    
    '''<remarks/>
    Public Property A() As Byte
        Get
            Return Me.aField
        End Get
        Set
            Me.aField = value
            Me.RaisePropertyChanged("A")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class RouteElement
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private nameField As String
    
    Private raceIDField As String
    
    Private trackColorField As RouteColor
    
    Private trackField() As RoutePoint
    
    '''<remarks/>
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
            Me.RaisePropertyChanged("Name")
        End Set
    End Property
    
    '''<remarks/>
    Public Property RaceID() As String
        Get
            Return Me.raceIDField
        End Get
        Set
            Me.raceIDField = value
            Me.RaisePropertyChanged("RaceID")
        End Set
    End Property
    
    '''<remarks/>
    Public Property TrackColor() As RouteColor
        Get
            Return Me.trackColorField
        End Get
        Set
            Me.trackColorField = value
            Me.RaisePropertyChanged("TrackColor")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("TrackPoint", IsNullable:=false)>  _
    Public Property Track() As RoutePoint()
        Get
            Return Me.trackField
        End Get
        Set
            Me.trackField = value
            Me.RaisePropertyChanged("Track")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
Partial Public Class RouteExportRouteList
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private routeField As RouteElement
    
    '''<remarks/>
    Public Property Route() As RouteElement
        Get
            Return Me.routeField
        End Get
        Set
            Me.routeField = value
            Me.RaisePropertyChanged("Route")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class
