'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Routeur.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [DBVersion] (
        '''[VersionNumber] iNTEGER  UNIQUE NOT NULL PRIMARY KEY,
        '''[VersionDate] TIMESTAMP DEFAULT CURRENT_TIMESTAMP UNIQUE NOT NULL
        ''');
        '''
        '''CREATE TABLE [MapsSegments] (
        '''[IdSegment] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
        '''[MapLevel] iNTEGER  NOT NULL,
        '''[Lon1] reAL  NOT NULL,
        '''[lat1] rEAL  NOT NULL,
        '''[lon2] rEAL  NOT NULL,
        '''[lat2] rEAL  NOT NULL
        ''');
        '''
        '''CREATE INDEX [IdxSegments] ON [MapsSegments](
        '''[MapLevel]  ASC,
        '''[Lon1]  ASC,
        '''[lat1]  ASC
        ''');
        '''
        '''insert into DBVersion(VersionNumber)  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateDBScript() As String
            Get
                Return ResourceManager.GetString("CreateDBScript", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to CREATE VIRTUAL TABLE MapLevel_Idx1 USING rtree(
        '''   id,              -- Integer primary key
        '''   minX, maxX,      -- Minimum and maximum X coordinate
        '''   minY, maxY       -- Minimum and maximum Y coordinate
        ''');
        '''CREATE VIRTUAL TABLE MapLevel_Idx2 USING rtree(
        '''   id,              -- Integer primary key
        '''   minX, maxX,      -- Minimum and maximum X coordinate
        '''   minY, maxY       -- Minimum and maximum Y coordinate
        ''');
        '''CREATE VIRTUAL TABLE MapLevel_Idx3 USING rtree(
        '''   id,              -- Integer primary ke [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateRangeIndex() As String
            Get
                Return ResourceManager.GetString("CreateRangeIndex", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to begin transaction;
        '''
        '''insert into DBVersion (VersionNumber) Values (2);
        '''
        '''CREATE TABLE `Tracks`
        '''(
        '''       ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        '''       RaceId INTEGER NOT NULL,
        '''       BoatNum INTEGER NOT NULL
        ''');
        '''
        '''CREATE TABLE `TrackPoints`
        '''(
        '''       RefTrack INTEGER NOT NULL,
        '''       IdPoint INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        '''       PointDate DATETIME NOT NULL,
        '''       Lon FLOAT NOT NULL,
        '''       Lat FLOAT NOT NULL
        ''');
        '''
        '''commit transaction;.
        '''</summary>
        Friend ReadOnly Property UpdateV1ToV2() As String
            Get
                Return ResourceManager.GetString("UpdateV1ToV2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to begin transaction;
        '''insert into DBVersion (VersionNumber) Values (3);
        '''drop table TrackPoints;
        '''CREATE TABLE `TrackPoints`
        '''(
        '''       RefTrack INTEGER NOT NULL,
        '''       IdPoint INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        '''       PointDate INTEGER NOT NULL,
        '''       Lon FLOAT NOT NULL,
        '''       Lat FLOAT NOT NULL
        ''');
        '''CREATE UNIQUE INDEX IdxTrackPoints
        ''' ON `TrackPoints` (RefTrack,PointDate);
        '''Commit transaction;.
        '''</summary>
        Friend ReadOnly Property UpdateV2ToV3() As String
            Get
                Return ResourceManager.GetString("UpdateV2ToV3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to begin transaction;
        '''insert into DBVersion (VersionNumber) Values (4);
        '''Analyze;
        '''Commit Transaction;.
        '''</summary>
        Friend ReadOnly Property UpdateV3ToV4() As String
            Get
                Return ResourceManager.GetString("UpdateV3ToV4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to begin transaction;
        '''insert into DBVersion (VersionNumber) Values (5);
        '''Create unique Index Idx_Tracks_RaceIDBoatID on Tracks (RaceID,BoatNum);
        '''Commit Transaction;.
        '''</summary>
        Friend ReadOnly Property UpdateV4ToV5() As String
            Get
                Return ResourceManager.GetString("UpdateV4ToV5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to begin transaction;
        '''insert into DBVersion (VersionNumber) Values (6);
        '''CREATE TABLE `MapImage`
        '''(
        '''       IdMapImage INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        '''	   Hash NVARCHAR(32) NOT NULL,
        '''       Data BLOB NOT NULL
        ''');
        '''CREATE UNIQUE INDEX IdxMapImageHash
        ''' ON `MapImage` (Hash);
        ''' 
        '''CREATE TABLE `MapLut`
        '''(
        '''       IdMapLut INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        '''       Level INTEGER NOT NULL,
        '''       X INTEGER NOT NULL,
        '''       Y INTEGER NOT NULL,
        '''	   RefBlob INTEGER NOT NULL,
        '''	   FOREIGN KEY( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpdateV5ToV6() As String
            Get
                Return ResourceManager.GetString("UpdateV5ToV6", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
